version: '3.4'

x-logging:
  &default-logging
  driver: loki
  options:
    loki-url: "http://host.dokcker.internal:3100/loki/api/v1/push"


services:  
  influxdb:
#    logging: *default-logging
    image: influxdb
    container_name: influxdb
    restart: always
    user: "1000" 
    ports:
      - 8086:8086
      - "25826:25826/udp"
    volumes:
      - ./influxdata:/var/lib/influxdb
      - ./config:/etc/influxdb/
      - ./collectdata/types.db:/usr/share/collectd/types.db:ro
    environment:
      - INFLUXDB_DB=db

      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=hello 

  web:
#    logging: *default-logging
    image: web
    restart: always
    container_name: webserver
    environment:
      - DJANGO_SECRET_KEY=local
    build: ./
    volumes:
      - ./:/code
    ports:
      - 8000:8000
    depends_on:
      - influxdb


  grafana:
#    logging: *default-logging
    image: grafana/grafana
    container_name: grafana
    restart: always
    user: "1000" 
    ports:
      - 3000:3000
    volumes:
      - ./gfdata:/var/lib/grafana
    depends_on:
      - influxdb
    
#
#  loki:
#    logging: *default-logging
#    image: grafana/loki
#    container_name: loki
#    restart: always
#    ports:
#      - 3100:3100
#    volumes: 
#      - ./config:/config
#    command: -config.file=/config/config-loki.yml

  # promtail:
  #   logging: *default-logging
  #   image: grafana/promtail
  #   volumes:
  #     - /var/log:/var/log
  #     - ./:/config
  #   command: -config.file=/config/config-prom.yml
  #   ports:
  #    - 9080:9080
